import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { v7 as uuidv7 } from "uuid";

import { apiGet } from "@/app/api/client";
import { useResource } from "@/app/hooks/use-resource";
import { Field, FormError, Select, TextArea, TextInput } from "@/components/design-system/FormFields";
import { EmptyState, Panel, StatusMark } from "@/components/design-system/Panel";

interface Account extends Record<string, unknown> { id: string; name: string; accountType: string; currencyCode: string }
interface BrokerageAccount extends Record<string, unknown> { id: string; displayName: string; financialAccountId: string; providerKey: string }
interface Preview { encoding: string; delimiter: string; headers: string[]; rows: Array<Record<string, string>>; parseErrors: Array<Record<string, unknown>>; fileSha256: string; totalRows: number }

async function postForm<T>(path: string, form: FormData): Promise<T> {
  const response = await fetch(path, { method: "POST", body: form });
  const body = await response.json() as T & { error?: { message?: string } };
  if (!response.ok) throw new Error(body.error?.message ?? `匯入失敗（HTTP ${response.status}）`);
  return body;
}

export function InvestmentImportPanel() {
  const accounts = useResource<Account>("financial-accounts");
  const brokerages = useResource<BrokerageAccount>("brokerage-accounts");
  const batches = useQuery({ queryKey: ["imports"], queryFn: () => apiGet<{ data: Array<Record<string, unknown>> }>("/api/v1/imports").then((response) => response.data) });
  const queryClient = useQueryClient();
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<Preview | null>(null); const [result, setResult] = useState<Record<string, unknown> | null>(null); const [error, setError] = useState<unknown>(null); const [busy, setBusy] = useState(false);
  const addBrokerage = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); brokerages.create.mutate({ financialAccountId: form.get("financialAccountId"), providerKey: "firstrade", displayName: form.get("displayName"), externalAccountHint: form.get("externalAccountHint") || null }, { onSuccess: () => formElement.reset() }); };
  const previewFile = async (selected: File) => { setFile(selected); setPreview(null); setResult(null); setError(null); const form = new FormData(); form.set("file", selected); setBusy(true); try { const response = await postForm<{ data: Preview }>("/api/v1/imports/csv/preview", form); setPreview(response.data); } catch (caught) { setError(caught); } finally { setBusy(false); } };
  const commit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!file || !preview) return; setBusy(true); setError(null); const source = new FormData(event.currentTarget); try { const typeMap = JSON.parse(String(source.get("typeMap"))); const profile = { date: source.get("date"), type: source.get("type"), amount: source.get("amount"), description: source.get("description") || undefined, symbol: source.get("symbol") || undefined, quantity: source.get("quantity") || undefined, currency: source.get("currency") || undefined, transactionId: source.get("transactionId") || undefined, typeMap, dateFormat: source.get("dateFormat"), defaultCurrency: String(source.get("defaultCurrency")).toUpperCase(), minorUnitScale: Number(source.get("minorUnitScale")) }; const form = new FormData(); form.set("file", file); form.set("operationId", uuidv7()); form.set("brokerageAccountId", String(source.get("brokerageAccountId"))); form.set("profileName", String(source.get("profileName"))); form.set("profile", JSON.stringify(profile)); const response = await postForm<{ data: Record<string, unknown> }>("/api/v1/imports/firstrade", form); setResult(response.data); await queryClient.invalidateQueries({ queryKey: ["imports"] }); } catch (caught) { setError(caught); } finally { setBusy(false); } };
  const headers = preview?.headers ?? [];
  const headerSelect = (name: string, required = false) => <Select name={name} required={required}><option value="">{required ? "請選擇" : "不使用"}</option>{headers.map((header) => <option key={header} value={header}>{header}</option>)}</Select>;
  return <Panel title="Firstrade CSV 正式匯入" index="08" tone="accent">
    <div className="split-layout"><form className="form-grid" onSubmit={addBrokerage}><Field label="財務券商帳戶"><Select name="financialAccountId" required><option value="">請選擇</option>{accounts.list.data?.filter((account) => account.accountType === "BROKERAGE").map((account) => <option key={account.id} value={account.id}>{account.name} · {account.currencyCode}</option>)}</Select></Field><Field label="匯入帳戶名稱"><TextInput name="displayName" required /></Field><Field label="遮蔽帳號提示"><TextInput name="externalAccountHint" placeholder="例如末四碼；不可填密碼" /></Field><FormError error={brokerages.create.error} /><button className="button">建立 Firstrade 匯入帳戶</button></form><div><Field label="選擇 CSV"><TextInput type="file" accept=".csv,text/csv" onChange={(event) => { const selected = event.target.files?.[0]; if (selected) void previewFile(selected); }} /></Field>{busy ? <p>驗證中…</p> : null}{preview ? <dl className="status-grid section-break"><div><dt>編碼</dt><dd>{preview.encoding}</dd></div><div><dt>分隔符</dt><dd>{preview.delimiter}</dd></div><div><dt>總列數</dt><dd>{preview.totalRows}</dd></div><div><dt>解析錯誤</dt><dd>{preview.parseErrors.length}</dd></div></dl> : <EmptyState title="尚未選擇 CSV" detail="只讀取使用者選擇的本機檔案，不使用Firstrade帳密或逆向登入。" />}</div></div>
    {preview ? <form className="form-grid form-grid--wide section-break" onSubmit={(event) => void commit(event)}><Field label="券商匯入帳戶"><Select name="brokerageAccountId" required><option value="">請選擇</option>{brokerages.list.data?.filter((item) => item.providerKey === "firstrade").map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</Select></Field><Field label="映射設定名稱"><TextInput name="profileName" required /></Field><Field label="日期欄">{headerSelect("date", true)}</Field><Field label="活動類型欄">{headerSelect("type", true)}</Field><Field label="金額欄">{headerSelect("amount", true)}</Field><Field label="說明欄">{headerSelect("description")}</Field><Field label="代號欄">{headerSelect("symbol")}</Field><Field label="數量欄">{headerSelect("quantity")}</Field><Field label="幣別欄">{headerSelect("currency")}</Field><Field label="交易識別欄">{headerSelect("transactionId")}</Field><Field label="日期格式"><Select name="dateFormat"><option value="AUTO">自動</option><option value="ISO">ISO</option><option value="US">美式月／日／年</option></Select></Field><Field label="預設幣別"><TextInput name="defaultCurrency" defaultValue="USD" pattern="[A-Za-z]{3}" required /></Field><Field label="小數位"><TextInput name="minorUnitScale" type="number" min="0" max="6" defaultValue="2" required /></Field><Field label="活動映射 JSON" hint="左側為CSV原始值；右側只允許正式活動類型"><TextArea name="typeMap" rows={8} defaultValue={'{\n  "BUY": "BUY",\n  "SELL": "SELL",\n  "DIVIDEND": "DIVIDEND",\n  "INTEREST": "INTEREST",\n  "DEPOSIT": "DEPOSIT",\n  "WITHDRAWAL": "WITHDRAWAL",\n  "FEE": "FEE"\n}'} required /></Field><FormError error={error} /><button className="button" disabled={busy}>驗證並提交整批</button></form> : null}
    {preview?.rows.length ? <div className="data-table-wrap section-break"><table className="data-table"><thead><tr><th>列</th>{preview.headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{preview.rows.slice(0, 10).map((row, index) => <tr key={index}><td>{index + 2}</td>{preview.headers.map((header) => <td key={header}>{row[header]}</td>)}</tr>)}</tbody></table></div> : null}
    {result ? <p className="success-line">批次 {String(result.batchId)}：共 {String(result.totalRows)} 列，匯入 {String(result.importedRows)}、重複 {String(result.duplicateRows)}、錯誤／待人工 {String(result.errorRows)}。</p> : null}
    <div className="data-table-wrap section-break"><table className="data-table"><thead><tr><th>檔案</th><th>狀態</th><th>總列</th><th>匯入／重複／錯誤</th><th>證據雜湊</th></tr></thead><tbody>{batches.data?.filter((batch) => batch.provider_key === "firstrade").map((batch) => <tr key={String(batch.id)}><td>{String(batch.original_filename)}</td><td><StatusMark tone={batch.status === "COMPLETED" ? "good" : batch.status === "FAILED" ? "danger" : "warn"}>{String(batch.status)}</StatusMark></td><td>{String(batch.total_rows)}</td><td>{String(batch.imported_rows)}／{String(batch.duplicate_rows)}／{String(batch.error_rows)}</td><td><code>{String(batch.file_sha256).slice(0, 16)}…</code></td></tr>)}</tbody></table></div>
  </Panel>;
}
