import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { v7 as uuidv7 } from "uuid";

import { apiGet, apiPost } from "@/app/api/client";
import { StructuredCsvImport } from "@/app/components/StructuredCsvImport";
import { useResource } from "@/app/hooks/use-resource";
import { MetricLineChart } from "@/components/charts/MetricLineChart";
import { Field, FormError, Select, TextArea, TextInput } from "@/components/design-system/FormFields";
import { PageHeader } from "@/components/design-system/PageHeader";
import { EmptyState, Panel, StatusMark } from "@/components/design-system/Panel";

interface Metric extends Record<string, unknown> { id: string; key: string; name: string; valueType: string; unit: string; role: "ACTION" | "SYSTEM" | "CONDITION" | "CAPABILITY" | "OUTCOME"; version: number }
interface EventType extends Record<string, unknown> { id: string; name: string; version: number; archivedAt?: string | null }
interface Area extends Record<string, unknown> { id: string; name: string }
interface Business extends Record<string, unknown> { id: string; name: string; areaId: string }

export function MetricsPage() {
  const metrics = useResource<Metric>("metrics", "?includeArchived=true");
  const observations = useResource<Record<string, unknown>>("metric-observations", "?limit=100");
  const eventTypes = useResource<EventType>("event-types", "?includeArchived=true");
  const events = useResource<Record<string, unknown>>("events", "?limit=100");
  const tags = useResource<Record<string, unknown>>("tags", "?includeArchived=true");
  const areas = useResource<Area>("areas"); const businesses = useResource<Business>("businesses");
  const queryClient = useQueryClient();
  const formulaList = useQuery({ queryKey: ["formula-list"], queryFn: () => apiGet<{ data: Array<Record<string, unknown>> }>("/api/v1/formulas").then((response) => response.data) });
  const [formulaResult, setFormulaResult] = useState<Record<string, unknown> | null>(null);
  const [selectedMetricId, setSelectedMetricId] = useState("");
  const validateFormula = useMutation({
    mutationFn: (expression: string) => apiPost<{ data: Record<string, unknown> }>("/api/v1/formulas/validate", { expression }).then((response) => response.data),
    onSuccess: setFormulaResult,
  });

  const addMetric = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement);
    metrics.create.mutate({ key: form.get("key"), name: form.get("name"), unit: form.get("unit"), valueType: form.get("valueType"), role: form.get("role"), domain: form.get("domain"), areaId: form.get("areaId") || null, businessId: form.get("businessId") || null, recordingFrequency: form.get("frequency"), sourcePolicy: "MANUAL", precision: Number(form.get("precision")) }, { onSuccess: () => formElement.reset() });
  };
  const addObservation = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const metric = metrics.list.data?.find((item) => item.id === form.get("metricId")); if (!metric) return;
    const raw = String(form.get("value")); const numeric = metric.valueType !== "TEXT";
    observations.create.mutate({ metricDefinitionId: metric.id, observedAt: new Date(String(form.get("observedAt"))).toISOString(), inputLocalDate: String(form.get("observedAt")).slice(0, 10), inputTimezone: "Asia/Taipei", valueDecimal: numeric ? raw : null, valueText: numeric ? null : raw, quality: "MANUAL", sourceRefType: null, sourceRefId: null, sourceType: "MANUAL" }, { onSuccess: () => formElement.reset() });
  };
  const editObservation = (event: FormEvent<HTMLFormElement>, observation: Record<string, unknown>, metric: Metric) => { event.preventDefault(); const form = new FormData(event.currentTarget); const raw = String(form.get("value")); const numeric = metric.valueType !== "TEXT"; const observedAt = new Date(String(form.get("observedAt"))).toISOString(); observations.update.mutate({ id: String(observation.id), version: Number(observation.version), patch: { observedAt, inputLocalDate: observedAt.slice(0, 10), valueDecimal: numeric ? raw : null, valueText: numeric ? null : raw } }); };
  const addEventType = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); eventTypes.create.mutate({ name: form.get("name"), colorToken: form.get("colorToken") }, { onSuccess: () => formElement.reset() }); };
  const addTag = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); tags.create.mutate({ name: form.get("name"), colorToken: form.get("colorToken") }, { onSuccess: () => formElement.reset() }); };
  const addEvent = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const startsAt = new Date(String(form.get("startsAt"))).toISOString(); const rawEnd = String(form.get("endsAt")); events.create.mutate({ eventTypeId: form.get("eventTypeId"), areaId: form.get("areaId") || null, businessId: form.get("businessId") || null, title: form.get("title"), description: form.get("description"), startsAt, endsAt: rawEnd ? new Date(rawEnd).toISOString() : null, inputTimezone: "Asia/Taipei", sourceReference: form.get("sourceReference") || null, sourceType: "MANUAL" }, { onSuccess: () => formElement.reset() }); };
  const editEvent = (event: FormEvent<HTMLFormElement>, item: Record<string, unknown>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const startsAt = new Date(String(form.get("startsAt"))).toISOString(); const rawEnd = String(form.get("endsAt")); events.update.mutate({ id: String(item.id), version: Number(item.version), patch: { eventTypeId: form.get("eventTypeId"), areaId: form.get("areaId") || null, businessId: form.get("businessId") || null, title: form.get("title"), description: form.get("description"), startsAt, endsAt: rawEnd ? new Date(rawEnd).toISOString() : null, sourceReference: form.get("sourceReference") || null } }); };
  const editMetric = (event: FormEvent<HTMLFormElement>, metric: Metric) => { event.preventDefault(); const form = new FormData(event.currentTarget); metrics.update.mutate({ id: metric.id, version: metric.version, patch: { key: form.get("key"), name: form.get("name"), unit: form.get("unit"), valueType: form.get("valueType"), role: form.get("role"), domain: form.get("domain"), areaId: form.get("areaId") || null, businessId: form.get("businessId") || null, recordingFrequency: form.get("frequency"), precision: Number(form.get("precision")) } }); };
  const editEventType = (event: FormEvent<HTMLFormElement>, row: EventType) => { event.preventDefault(); const form = new FormData(event.currentTarget); eventTypes.update.mutate({ id: row.id, version: row.version, patch: { name: form.get("name"), colorToken: form.get("colorToken") } }); };
  const editTag = (event: FormEvent<HTMLFormElement>, row: Record<string, unknown>) => { event.preventDefault(); const form = new FormData(event.currentTarget); tags.update.mutate({ id: String(row.id), version: Number(row.version), patch: { name: form.get("name"), colorToken: form.get("colorToken") } }); };
  const saveFormula = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const expression = String(form.get("expression")); await apiPost("/api/v1/formulas", { operationId: uuidv7(), data: { id: uuidv7(), metricDefinitionId: form.get("metricDefinitionId"), formulaVersion: Number(form.get("formulaVersion")), expression, window: { kind: "ABSOLUTE_RANGE" }, missingPolicy: form.get("missingPolicy") } }); await queryClient.invalidateQueries({ queryKey: ["formula-list"] }); formElement.reset(); setFormulaResult(null); };
  const calculateFormula = async (formula: Record<string, unknown>) => { const to = new Date().toISOString(); const from = `${to.slice(0, 4)}-01-01T00:00:00.000Z`; const response = await apiPost<{ data: Record<string, unknown> }>(`/api/v1/formulas/${String(formula.id)}/calculate`, { from, to }); setFormulaResult(response.data); };
  const selectedMetric = metrics.list.data?.find((metric) => metric.id === selectedMetricId);
  const selectedObservations = observations.list.data?.filter((observation) => observation.metricDefinitionId === selectedMetricId).sort((left, right) => String(left.observedAt).localeCompare(String(right.observedAt))) ?? [];
  const metricChartProvenance = selectedMetric ? {
    metricKey: selectedMetric.key,
    formulaVersion: 1,
    quality: [...new Set(selectedObservations.map((row) => String(row.quality)))].join("+") || "INSUFFICIENT",
    observationCount: selectedObservations.length,
    excludedCount: 0,
    window: { kind: "OBSERVED_AT_RANGE", from: selectedObservations[0]?.observedAt ?? null, to: selectedObservations.at(-1)?.observedAt ?? null, timezone: "Asia/Taipei" },
    filters: { metricDefinitionId: selectedMetric.id, role: selectedMetric.role },
    grouping: ["observedAt"],
    aggregation: "NONE_RAW_SERIES",
    denominatorDefinition: null,
  } : null;
  const roleLabels: Record<Metric["role"], string> = { ACTION: "行動", SYSTEM: "系統", CONDITION: "條件", CAPABILITY: "能力", OUTCOME: "結果" };

  return <div className="page">
    <PageHeader eyebrow="MEASURE / CONTEXT" title="指標、安全公式與事件時間軸" description="指標角色與單位保持可讀；自定義公式只經過白名單解析器，不執行任意程式碼。" />
    <div className="split-layout">
      <Panel title="定義指標" index="01" tone="accent"><form className="form-grid" onSubmit={addMetric}><Field label="識別鍵"><TextInput name="key" pattern="[a-z][a-z0-9_.-]+" required /></Field><Field label="名稱"><TextInput name="name" required /></Field><Field label="單位"><TextInput name="unit" required /></Field><Field label="值類型"><Select name="valueType"><option value="DECIMAL">小數</option><option value="INTEGER">整數</option><option value="PERCENTAGE">百分比</option><option value="DURATION">時間</option><option value="TEXT">文字</option></Select></Field><Field label="角色"><Select name="role"><option value="ACTION">行動</option><option value="SYSTEM">系統</option><option value="CONDITION">狀態</option><option value="CAPABILITY">能力</option><option value="OUTCOME">結果</option></Select></Field><Field label="領域名稱"><TextInput name="domain" required /></Field><Field label="人生領域"><Select name="areaId"><option value="">不指定</option>{areas.list.data?.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</Select></Field><Field label="事業"><Select name="businessId"><option value="">不指定</option>{businesses.list.data?.map((business) => <option key={business.id} value={business.id}>{business.name}</option>)}</Select></Field><Field label="紀錄頻率"><TextInput name="frequency" defaultValue="AD_HOC" required /></Field><Field label="顯示精度"><TextInput name="precision" type="number" min="0" max="12" defaultValue="2" required /></Field><FormError error={metrics.create.error} /><button className="button">建立指標</button></form></Panel>
      <Panel title="記錄觀測" index="02"><form className="form-grid" onSubmit={addObservation}>{metrics.list.data?.some((item) => !item.archivedAt) ? <><Field label="指標"><Select name="metricId" required><option value="">請選擇</option>{metrics.list.data.filter((item) => !item.archivedAt).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.unit}</option>)}</Select></Field><Field label="觀測時間"><TextInput name="observedAt" type="datetime-local" required /></Field><Field label="值"><TextInput name="value" required /></Field><FormError error={observations.create.error} /><button className="button">保存觀測</button></> : <EmptyState title="尚無指標" detail="先建立有正式單位與角色的指標。" />}</form></Panel>
    </div>
    <Panel title="安全公式" index="03"><form className="form-grid" onSubmit={(event) => void saveFormula(event)}><Field label="輸出指標"><Select name="metricDefinitionId" required><option value="">請選擇</option>{metrics.list.data?.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.unit}</option>)}</Select></Field><Field label="公式版本"><TextInput name="formulaVersion" type="number" min="1" defaultValue="1" required /></Field><Field label="公式"><TextInput name="expression" placeholder="conversions / impressions * 100" required onBlur={(event) => validateFormula.mutate(event.target.value)} /></Field><Field label="缺失資料策略"><Select name="missingPolicy"><option value="FAIL">停止並明示缺失</option><option value="EXCLUDE">回傳資料不足</option><option value="ZERO">明確補零</option></Select></Field><button className="button">驗證並保存版本</button></form><FormError error={validateFormula.error} /><p className="support-copy">允許數字、指標鍵、括號、＋－×÷及 SUM／AVG／COUNT／LAST／DELTA；不執行 JavaScript。</p>{formulaList.data?.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>輸出</th><th>版本</th><th>公式</th><th>缺失策略</th><th>操作</th></tr></thead><tbody>{formulaList.data.map((formula) => <tr key={String(formula.id)}><td>{String(formula.metric_name)}</td><td>{String(formula.formula_version)}</td><td><code>{String(formula.expression)}</code></td><td>{String(formula.missing_policy)}</td><td><button className="button button--quiet" onClick={() => void calculateFormula(formula)}>計算今年資料</button></td></tr>)}</tbody></table></div> : null}{formulaResult ? <pre className="code-result">{JSON.stringify(formulaResult, null, 2)}</pre> : null}</Panel>
    <Panel title="指標、事件類型與標籤管理" index="03A">
      <div className="data-table-wrap"><table className="data-table"><thead><tr><th>指標</th><th>角色／單位</th><th>領域／事業</th><th>狀態</th><th>操作</th></tr></thead><tbody>{metrics.list.data?.map((metric) => <tr key={metric.id}><td>{metric.name}<small>{metric.key}</small></td><td>{roleLabels[metric.role]} · {metric.unit}</td><td>{areas.list.data?.find((area) => area.id === metric.areaId)?.name ?? "—"}／{businesses.list.data?.find((business) => business.id === metric.businessId)?.name ?? "—"}</td><td>{metric.archivedAt ? "已封存" : "啟用"}</td><td><details className="inline-editor"><summary>編輯指標</summary><form className="form-grid" onSubmit={(event) => editMetric(event, metric)}><Field label="識別鍵"><TextInput name="key" defaultValue={metric.key} required /></Field><Field label="名稱"><TextInput name="name" defaultValue={metric.name} required /></Field><Field label="單位"><TextInput name="unit" defaultValue={metric.unit} required /></Field><Field label="值類型"><Select name="valueType" defaultValue={metric.valueType}><option value="DECIMAL">小數</option><option value="INTEGER">整數</option><option value="PERCENTAGE">百分比</option><option value="DURATION">時間</option><option value="TEXT">文字</option></Select></Field><Field label="角色"><Select name="role" defaultValue={metric.role}><option value="ACTION">行動</option><option value="SYSTEM">系統</option><option value="CONDITION">狀態</option><option value="CAPABILITY">能力</option><option value="OUTCOME">結果</option></Select></Field><Field label="領域名稱"><TextInput name="domain" defaultValue={String(metric.domain)} required /></Field><Field label="人生領域"><Select name="areaId" defaultValue={String(metric.areaId ?? "")}><option value="">不指定</option>{areas.list.data?.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</Select></Field><Field label="事業"><Select name="businessId" defaultValue={String(metric.businessId ?? "")}><option value="">不指定</option>{businesses.list.data?.map((business) => <option key={business.id} value={business.id}>{business.name}</option>)}</Select></Field><Field label="紀錄頻率"><TextInput name="frequency" defaultValue={String(metric.recordingFrequency)} required /></Field><Field label="精度"><TextInput name="precision" type="number" min="0" max="12" defaultValue={Number(metric.precision)} required /></Field><button className="button">保存</button><button className="button button--quiet" type="button" onClick={() => metrics.archive.mutate({ id: metric.id, version: metric.version, restore: Boolean(metric.archivedAt) })}>{metric.archivedAt ? "恢復" : "封存"}</button></form></details></td></tr>)}</tbody></table></div>
      <div className="data-table-wrap"><table className="data-table"><thead><tr><th>類別</th><th>名稱</th><th>色彩代碼</th><th>狀態</th><th>操作</th></tr></thead><tbody>{eventTypes.list.data?.map((row) => <tr key={row.id}><td>事件類型</td><td>{row.name}</td><td>{String(row.colorToken)}</td><td>{row.archivedAt ? "已封存" : "啟用"}</td><td><details className="inline-editor"><summary>編輯</summary><form className="inline-form" onSubmit={(event) => editEventType(event, row)}><Field label="名稱"><TextInput name="name" defaultValue={row.name} required /></Field><Field label="色彩"><TextInput name="colorToken" defaultValue={String(row.colorToken)} required /></Field><button className="button">保存</button><button className="button button--quiet" type="button" onClick={() => eventTypes.archive.mutate({ id: row.id, version: row.version, restore: Boolean(row.archivedAt) })}>{row.archivedAt ? "恢復" : "封存"}</button></form></details></td></tr>)}{tags.list.data?.map((row) => <tr key={String(row.id)}><td>標籤</td><td>{String(row.name)}</td><td>{String(row.colorToken)}</td><td>{row.archivedAt ? "已封存" : "啟用"}</td><td><details className="inline-editor"><summary>編輯</summary><form className="inline-form" onSubmit={(event) => editTag(event, row)}><Field label="名稱"><TextInput name="name" defaultValue={String(row.name)} required /></Field><Field label="色彩"><TextInput name="colorToken" defaultValue={String(row.colorToken)} required /></Field><button className="button">保存</button><button className="button button--quiet" type="button" onClick={() => tags.archive.mutate({ id: String(row.id), version: Number(row.version), restore: Boolean(row.archivedAt) })}>{row.archivedAt ? "恢復" : "封存"}</button></form></details></td></tr>)}</tbody></table></div>
      <FormError error={metrics.update.error || metrics.archive.error || eventTypes.update.error || eventTypes.archive.error || tags.update.error || tags.archive.error} />
    </Panel>
    <div className="split-layout">
      <Panel title="事件類型與標籤" index="04"><form className="inline-form" onSubmit={addEventType}><Field label="事件類型"><TextInput name="name" required /></Field><Field label="色彩代碼"><TextInput name="colorToken" defaultValue="event" pattern="[a-z][a-z0-9-]*" required /></Field><button className="button">新增類型</button></form><form className="inline-form section-break" onSubmit={addTag}><Field label="標籤名稱"><TextInput name="name" required /></Field><Field label="色彩代碼"><TextInput name="colorToken" defaultValue="neutral" pattern="[a-z][a-z0-9-]*" required /></Field><button className="button button--quiet">新增標籤</button></form>{tags.list.data?.length ? <p className="support-copy">現有標籤：{tags.list.data.map((tag) => String(tag.name)).join("、")}</p> : null}</Panel>
      <Panel title="新增事件" index="05">{eventTypes.list.data?.some((item) => !item.archivedAt) ? <form className="form-grid" onSubmit={addEvent}><Field label="類型"><Select name="eventTypeId" required>{eventTypes.list.data.filter((item) => !item.archivedAt).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="人生領域"><Select name="areaId"><option value="">不指定</option>{areas.list.data?.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</Select></Field><Field label="事業"><Select name="businessId"><option value="">不指定</option>{businesses.list.data?.map((business) => <option key={business.id} value={business.id}>{business.name}</option>)}</Select></Field><Field label="標題"><TextInput name="title" required /></Field><Field label="開始"><TextInput name="startsAt" type="datetime-local" required /></Field><Field label="結束"><TextInput name="endsAt" type="datetime-local" /></Field><Field label="說明"><TextArea name="description" /></Field><Field label="來源參照"><TextInput name="sourceReference" /></Field><button className="button">保存事件</button></form> : <EmptyState title="尚無事件類型" detail="先建立事件類型後再登記事件。" />}</Panel>
    </div>
    <Panel title="最近時間軸" index="06">{!events.list.data?.length ? <EmptyState title="尚無事件" detail="發布、健康、財務或人生里程碑都可成為比較背景。" /> : <ol className="timeline">{events.list.data.map((item) => <li key={String(item.id)}><time>{new Date(String(item.startsAt)).toLocaleString("zh-TW")}</time><strong>{String(item.title)}</strong><StatusMark>{eventTypes.list.data?.find((type) => type.id === item.eventTypeId)?.name ?? "事件"}</StatusMark><p>{String(item.description || "尚無說明")}</p>{item.sourceType === "MANUAL" ? <details className="inline-editor"><summary>編輯事件</summary><form className="form-grid" onSubmit={(event) => editEvent(event, item)}><Field label="類型"><Select name="eventTypeId" defaultValue={String(item.eventTypeId)} required>{eventTypes.list.data?.filter((type) => !type.archivedAt || type.id === item.eventTypeId).map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</Select></Field><Field label="人生領域"><Select name="areaId" defaultValue={String(item.areaId ?? "")}><option value="">不指定</option>{areas.list.data?.map((area) => <option key={area.id} value={area.id}>{area.name}</option>)}</Select></Field><Field label="事業"><Select name="businessId" defaultValue={String(item.businessId ?? "")}><option value="">不指定</option>{businesses.list.data?.map((business) => <option key={business.id} value={business.id}>{business.name}</option>)}</Select></Field><Field label="標題"><TextInput name="title" defaultValue={String(item.title)} required /></Field><Field label="開始"><TextInput name="startsAt" type="datetime-local" defaultValue={String(item.startsAt).slice(0, 16)} required /></Field><Field label="結束"><TextInput name="endsAt" type="datetime-local" defaultValue={item.endsAt ? String(item.endsAt).slice(0, 16) : ""} /></Field><Field label="說明"><TextArea name="description" defaultValue={String(item.description ?? "")} /></Field><Field label="來源參照"><TextInput name="sourceReference" defaultValue={String(item.sourceReference ?? "")} /></Field><button className="button">保存修改</button><button className="button button--quiet" type="button" onClick={() => events.archive.mutate({ id: String(item.id), version: Number(item.version) })}>刪除</button></form></details> : null}</li>)}</ol>}</Panel>
    <Panel title="指標 CSV 匯入" index="07"><p className="support-copy">映射欄名後由後端預覽、驗證與去重；原始檔及逐列錯誤會保存為匯入證據。</p><StructuredCsvImport moduleKey="metrics" definitions={metrics.list.data?.map((metric) => ({ id: metric.id, label: `${metric.name} · ${metric.unit}` })) ?? []} onImported={async () => { await observations.list.refetch(); }} /></Panel>
    <Panel title="角色分組與時間序列" index="08" tone="accent" id="metric-observation-records">
      <div className="filter-bar"><Field label="查看指標"><Select value={selectedMetricId} onChange={(event) => setSelectedMetricId(event.target.value)}><option value="">請選擇</option>{metrics.list.data?.map((metric) => <option key={metric.id} value={metric.id}>{roleLabels[metric.role]} · {metric.name} · {metric.unit}</option>)}</Select></Field></div>
      <div className="metric-role-grid">{(Object.keys(roleLabels) as Metric["role"][]).map((role) => <section key={role}><h3>{roleLabels[role]} / {role}</h3>{metrics.list.data?.filter((metric) => metric.role === role).length ? <ul className="compact-list">{metrics.list.data.filter((metric) => metric.role === role).map((metric) => { const latest = observations.list.data?.filter((observation) => observation.metricDefinitionId === metric.id).sort((left, right) => String(right.observedAt).localeCompare(String(left.observedAt)))[0]; return <li key={metric.id}><strong>{metric.name}</strong><span>{latest ? `${String(latest.valueDecimal ?? latest.valueText)} ${metric.unit}` : "尚無觀測"}</span></li>; })}</ul> : <p className="support-copy">此角色尚無指標。</p>}</section>)}</div>
      {selectedMetric ? selectedMetric.valueType === "TEXT" ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>時間</th><th>值</th><th>角色</th><th>來源</th></tr></thead><tbody>{selectedObservations.map((row) => <tr key={String(row.id)}><td>{new Date(String(row.observedAt)).toLocaleString("zh-TW")}</td><td>{String(row.valueText)}</td><td>{roleLabels[selectedMetric.role]}</td><td>{String(row.sourceType)}</td></tr>)}</tbody></table></div> : <MetricLineChart title={`${selectedMetric.name}時間序列`} subtitle={`${roleLabels[selectedMetric.role]}角色；依實際觀測時間排序`} data={selectedObservations.map((row) => ({ observedAt: String(row.observedAt), value: Number(row.valueDecimal) }))} xKey="observedAt" xAxisName="觀測時間（Asia/Taipei）" yAxisName={selectedMetric.name} unit={selectedMetric.unit} series={[{ key: "value", name: selectedMetric.name, color: "#244f84" }]} definition={`原始${selectedMetric.valueType}指標；角色${selectedMetric.role}；不與其他角色合成單一分數。`} source="metric_observations；依每筆sourceType與sourceRef追溯" sampleSize={selectedObservations.length} missingCount={0} lastUpdated={selectedObservations.at(-1) ? String(selectedObservations.at(-1)?.updatedAt ?? selectedObservations.at(-1)?.observedAt) : null} provenance={metricChartProvenance} evidenceHref="#metric-observation-records" /> : <EmptyState title="請選擇一個指標" detail="角色分組保持獨立，不會把行動、能力與結果混成單一分數。" />}
      {selectedMetric && selectedObservations.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>觀測時間</th><th>值</th><th>來源</th><th>操作</th></tr></thead><tbody>{selectedObservations.map((row) => <tr key={String(row.id)}><td>{new Date(String(row.observedAt)).toLocaleString("zh-TW")}</td><td>{String(row.valueDecimal ?? row.valueText)} {selectedMetric.unit}</td><td>{String(row.sourceType)}</td><td>{row.sourceType === "MANUAL" ? <details className="inline-editor"><summary>編輯</summary><form className="form-grid" onSubmit={(event) => editObservation(event, row, selectedMetric)}><Field label="觀測時間"><TextInput name="observedAt" type="datetime-local" defaultValue={String(row.observedAt).slice(0, 16)} required /></Field><Field label="值"><TextInput name="value" defaultValue={String(row.valueDecimal ?? row.valueText)} required /></Field><button className="button">保存修改</button><button className="button button--quiet" type="button" onClick={() => observations.archive.mutate({ id: String(row.id), version: Number(row.version) })}>刪除</button></form></details> : <span>來源資料不可手動改寫</span>}</td></tr>)}</tbody></table></div> : null}
    </Panel>
  </div>;
}
