import { useQuery } from "@tanstack/react-query";
import { useState, type FormEvent } from "react";
import { v7 as uuidv7 } from "uuid";

import { apiGet, apiPost, createResource } from "@/app/api/client";
import { StructuredCsvImport } from "@/app/components/StructuredCsvImport";
import { useResource } from "@/app/hooks/use-resource";
import { MetricLineChart } from "@/components/charts/MetricLineChart";
import { Field, FormError, Select, TextArea, TextInput } from "@/components/design-system/FormFields";
import { PageHeader } from "@/components/design-system/PageHeader";
import { EmptyState, Panel, StatusMark } from "@/components/design-system/Panel";

interface Platform extends Record<string, unknown> { id: string; name: string; key: string; version: number; archivedAt?: string | null }
interface SocialAccount extends Record<string, unknown> { id: string; displayName: string; platformId: string; version: number; archivedAt?: string | null }
interface Content extends Record<string, unknown> { id: string; title: string; style: string; version: number; archivedAt?: string | null }
interface Post extends Record<string, unknown> { id: string; contentAssetId: string; publishedAt: string; version: number; archivedAt?: string | null }
interface SocialMetric extends Record<string, unknown> { id: string; metricKey: string; providerMetricName: string; scope: string; unit: string; isCumulative: boolean; version: number; archivedAt?: string | null }
interface Business extends Record<string, unknown> { id: string; name: string }
interface Tag extends Record<string, unknown> { id: string; name: string }
interface EventType extends Record<string, unknown> { id: string; name: string }
type ExposureAggregation = "MEAN" | "SUM" | "MEDIAN" | "DISTRIBUTION";
interface ComparisonDefinition extends Record<string, unknown> { id: string; name: string; metricKey: string; aggregation: ExposureAggregation; groupBy: string[]; filters: Record<string, string | null>; toleranceMinutes: number }

export function SocialPage() {
  const platforms = useResource<Platform>("platforms", "?includeArchived=true");
  const accounts = useResource<SocialAccount>("social-accounts", "?includeArchived=true");
  const content = useResource<Content>("content-assets", "?includeArchived=true");
  const posts = useResource<Post>("platform-posts", "?limit=100&includeArchived=true");
  const metrics = useResource<SocialMetric>("social-metrics", "?includeArchived=true");
  const snapshots = useResource<Record<string, unknown>>("social-snapshots", "?limit=100");
  const conversions = useResource<Record<string, unknown>>("conversions", "?limit=100");
  const events = useResource<Record<string, unknown>>("events", "?limit=100");
  const eventTypes = useResource<EventType>("event-types");
  const businesses = useResource<Business>("businesses"); const tags = useResource<Tag>("tags");
  const comparisonDefinitions = useResource<ComparisonDefinition>("comparison-definitions", "?includeArchived=true"); const savedViews = useResource<Record<string, unknown>>("saved-views", "?moduleKey=social&includeArchived=true");
  const [metricKey, setMetricKey] = useState(""); const [tolerance, setTolerance] = useState(15);
  const [aggregation, setAggregation] = useState<ExposureAggregation>("MEAN");
  const [groupBy, setGroupBy] = useState("style"); const [platformFilter, setPlatformFilter] = useState(""); const [accountFilter, setAccountFilter] = useState("");
  const [businessFilter, setBusinessFilter] = useState(""); const [styleFilter, setStyleFilter] = useState(""); const [topicFilter, setTopicFilter] = useState(""); const [tagFilter, setTagFilter] = useState("");
  const [timelinePostId, setTimelinePostId] = useState(""); const [timelineMetricId, setTimelineMetricId] = useState("");
  const [timelineEventTypeId, setTimelineEventTypeId] = useState("");
  const today = new Date().toISOString().slice(0, 10);
  const comparisonParams = new URLSearchParams({ metricKey, aggregation, toleranceMinutes: String(tolerance), groupBy, from: `${today.slice(0, 4)}-01-01T00:00:00.000Z`, to: `${today}T23:59:59.999Z` });
  if (platformFilter) comparisonParams.set("platformKey", platformFilter); if (accountFilter) comparisonParams.set("accountId", accountFilter); if (businessFilter) comparisonParams.set("businessId", businessFilter); if (styleFilter) comparisonParams.set("style", styleFilter); if (topicFilter) comparisonParams.set("topic", topicFilter); if (tagFilter) comparisonParams.set("tag", tagFilter);
  const comparison = useQuery({ queryKey: ["social-comparison", comparisonParams.toString()], enabled: Boolean(metricKey), queryFn: () => apiGet<{ data: Record<string, unknown> }>(`/api/v1/social/comparison?${comparisonParams.toString()}`).then((response) => response.data) });
  const addPlatform = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); platforms.create.mutate({ key: form.get("key"), name: form.get("name"), providerKind: "MANUAL", metricNamespace: form.get("namespace") }, { onSuccess: () => formElement.reset() }); };
  const addAccount = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); accounts.create.mutate({ platformId: form.get("platformId"), displayName: form.get("displayName"), externalAccountId: null, accountKind: "UNKNOWN", timezone: "Asia/Taipei", sourceType: "MANUAL" }, { onSuccess: () => formElement.reset() }); };
  const addContent = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); content.create.mutate({ businessId: form.get("businessId") || null, title: form.get("title"), description: form.get("description"), topic: form.get("topic"), style: form.get("style"), format: form.get("format"), lengthValue: form.get("lengthValue") ? Number(form.get("lengthValue")) : null, lengthUnit: form.get("lengthUnit") || null, campaign: form.get("campaign") }, { onSuccess: () => formElement.reset() }); };
  const addContentTag = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); await apiPost("/api/v1/entity-tags", { operationId: uuidv7(), data: { entityType: "content_asset", entityId: form.get("contentAssetId"), tagId: form.get("tagId") } }); formElement.reset(); };
  const saveComparisonDefinition = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!metricKey) return; const formElement = event.currentTarget; const name = String(new FormData(formElement).get("name")); const filters = { platformKey: platformFilter || null, accountId: accountFilter || null, businessId: businessFilter || null, style: styleFilter || null, topic: topicFilter || null, tag: tagFilter || null }; const definitionId = uuidv7(); await createResource("comparison-definitions", { id: definitionId, name, metricKey, aggregation, groupBy: [groupBy], filters, windowFromHours: 0, windowToHours: 24, toleranceMinutes: tolerance }); await createResource("saved-views", { id: uuidv7(), name, moduleKey: "social", filter: { metricKey, aggregation, toleranceMinutes: tolerance, groupBy, ...filters }, chart: { kind: aggregation === "DISTRIBUTION" ? "FIRST_DAY_DISTRIBUTION" : "FIRST_DAY_COMPARISON", x: groupBy, y: metricKey, aggregation, formulaVersion: 1 } }); await Promise.all([comparisonDefinitions.list.refetch(), savedViews.list.refetch()]); formElement.reset(); };
  const applyComparisonDefinition = (definition: ComparisonDefinition) => { const filters = definition.filters ?? {}; setMetricKey(definition.metricKey); setAggregation(definition.aggregation); setGroupBy(definition.groupBy[0] ?? "style"); setTolerance(definition.toleranceMinutes); setPlatformFilter(filters.platformKey ?? ""); setAccountFilter(filters.accountId ?? ""); setBusinessFilter(filters.businessId ?? ""); setStyleFilter(filters.style ?? ""); setTopicFilter(filters.topic ?? ""); setTagFilter(filters.tag ?? ""); };
  const addPost = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); posts.create.mutate({ contentAssetId: form.get("contentAssetId"), socialAccountId: form.get("socialAccountId"), externalPostId: form.get("externalPostId") || null, permalink: form.get("permalink") || null, platformFormat: form.get("platformFormat"), publishedAt: new Date(String(form.get("publishedAt"))).toISOString(), publishedTimezone: "Asia/Taipei", sourceType: "MANUAL" }, { onSuccess: () => formElement.reset() }); };
  const addMetric = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); metrics.create.mutate({ platformId: form.get("platformId"), metricKey: form.get("metricKey"), providerMetricName: form.get("providerMetricName"), providerDefinition: form.get("providerDefinition"), providerDefinitionVersion: "manual-v1", unit: form.get("unit"), scope: form.get("scope"), isCumulative: form.get("isCumulative") === "on", comparableFamily: form.get("comparableFamily") || null, sourceType: "MANUAL" }, { onSuccess: () => formElement.reset() }); };
  const addSnapshot = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const metric = metrics.list.data?.find((item) => item.id === form.get("metricId")); if (!metric) return; const postId = form.get("platformPostId") || null; const accountId = postId ? null : form.get("socialAccountId") || null; const publishedAt = posts.list.data?.find((post) => post.id === postId)?.publishedAt ?? null; const observedAt = new Date(String(form.get("observedAt"))).toISOString(); const ageSeconds = publishedAt ? Math.max(0, Math.round((Date.parse(observedAt) - Date.parse(publishedAt)) / 1000)) : null; snapshots.create.mutate({ socialMetricDefinitionId: metric.id, socialAccountId: accountId, platformPostId: postId, observedAt, publishedAt, ageSeconds, valueDecimal: form.get("value"), isCumulative: metric.isCumulative, quality: "MANUAL", rawPayloadId: null, importRowId: null, sourceType: "MANUAL" }, { onSuccess: () => formElement.reset() }); };
  const editSocialSnapshot = (event: FormEvent<HTMLFormElement>, row: Record<string, unknown>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const observedAt = new Date(String(form.get("observedAt"))).toISOString(); const publishedAt = row.publishedAt ? String(row.publishedAt) : null; snapshots.update.mutate({ id: String(row.id), version: Number(row.version), patch: { observedAt, ageSeconds: publishedAt ? Math.max(0, Math.round((Date.parse(observedAt) - Date.parse(publishedAt)) / 1000)) : null, valueDecimal: form.get("value") } }, { onSuccess: () => void comparison.refetch() }); };
  const addConversion = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const post = posts.list.data?.find((item) => item.id === form.get("postId")); conversions.create.mutate({ platformPostId: post?.id ?? null, contentAssetId: post?.contentAssetId ?? null, campaign: form.get("campaign") || null, confirmedAt: new Date(String(form.get("confirmedAt"))).toISOString(), countValue: Number(form.get("countValue")), amountMinor: null, currencyCode: null, minorUnitScale: null, attributionNote: form.get("attributionNote"), denominatorMetricKey: form.get("denominatorMetricKey"), windowFromHours: 0, windowToHours: 24 }, { onSuccess: () => { formElement.reset(); void comparison.refetch(); } }); };
  const editConversion = (event: FormEvent<HTMLFormElement>, row: Record<string, unknown>) => { event.preventDefault(); const form = new FormData(event.currentTarget); conversions.update.mutate({ id: String(row.id), version: Number(row.version), patch: { countValue: Number(form.get("countValue")), confirmedAt: new Date(String(form.get("confirmedAt"))).toISOString(), attributionNote: form.get("attributionNote"), denominatorMetricKey: form.get("denominatorMetricKey") } }, { onSuccess: () => void comparison.refetch() }); };
  const editPlatform = (event: FormEvent<HTMLFormElement>, row: Platform) => { event.preventDefault(); const form = new FormData(event.currentTarget); platforms.update.mutate({ id: row.id, version: row.version, patch: { key: form.get("key"), name: form.get("name"), metricNamespace: form.get("namespace") } }); };
  const editAccount = (event: FormEvent<HTMLFormElement>, row: SocialAccount) => { event.preventDefault(); const form = new FormData(event.currentTarget); accounts.update.mutate({ id: row.id, version: row.version, patch: { platformId: form.get("platformId"), displayName: form.get("displayName"), accountKind: form.get("accountKind"), timezone: form.get("timezone") } }); };
  const editContent = (event: FormEvent<HTMLFormElement>, row: Content) => { event.preventDefault(); const form = new FormData(event.currentTarget); content.update.mutate({ id: row.id, version: row.version, patch: { businessId: form.get("businessId") || null, title: form.get("title"), description: form.get("description"), topic: form.get("topic"), style: form.get("style"), format: form.get("format"), lengthValue: form.get("lengthValue") ? Number(form.get("lengthValue")) : null, lengthUnit: form.get("lengthUnit") || null, campaign: form.get("campaign") } }); };
  const editPost = (event: FormEvent<HTMLFormElement>, row: Post) => { event.preventDefault(); const form = new FormData(event.currentTarget); posts.update.mutate({ id: row.id, version: row.version, patch: { contentAssetId: form.get("contentAssetId"), socialAccountId: form.get("socialAccountId"), externalPostId: form.get("externalPostId") || null, permalink: form.get("permalink") || null, platformFormat: form.get("platformFormat"), publishedAt: new Date(String(form.get("publishedAt"))).toISOString() } }); };
  const editMetric = (event: FormEvent<HTMLFormElement>, row: SocialMetric) => { event.preventDefault(); const form = new FormData(event.currentTarget); metrics.update.mutate({ id: row.id, version: row.version, patch: { platformId: form.get("platformId"), metricKey: form.get("metricKey"), providerMetricName: form.get("providerMetricName"), providerDefinition: form.get("providerDefinition"), unit: form.get("unit"), scope: form.get("scope"), isCumulative: form.get("isCumulative") === "on", comparableFamily: form.get("comparableFamily") || null } }); };
  const groups = (comparison.data?.groups as Array<Record<string, unknown>> | undefined) ?? [];
  const confounders = (comparison.data?.crossGroupConfounders as Array<{ field: string; groups: Record<string, string[]> }> | undefined) ?? [];
  const chartData = groups.map((group) => ({ group: String(group.group), exposure: Number((group.exposure as Record<string, unknown>).value) }));
  const groupLabels: Record<string, string> = { style: "內容風格", topic: "主題", platformKey: "平台", accountId: "帳號", businessId: "事業", tag: "標籤" };
  const aggregationLabels: Record<ExposureAggregation, string> = { MEAN: "平均", SUM: "總和", MEDIAN: "中位數", DISTRIBUTION: "分布" };
  const groupLabel = groupLabels[groupBy] ?? groupBy;
  const timelineMetric = metrics.list.data?.find((metric) => metric.id === timelineMetricId);
  const timelineSnapshots = snapshots.list.data?.filter((snapshot) => snapshot.platformPostId === timelinePostId && snapshot.socialMetricDefinitionId === timelineMetricId).sort((left, right) => String(left.observedAt).localeCompare(String(right.observedAt))) ?? [];
  const timelineData = timelineSnapshots.map((snapshot) => ({ observedAt: String(snapshot.observedAt), value: Number(snapshot.valueDecimal) }));
  const timelineMarkers = events.list.data?.filter((event) => !timelineEventTypeId || event.eventTypeId === timelineEventTypeId).map((event) => ({
    id: String(event.id),
    xValue: String(event.startsAt),
    label: String(event.title),
    description: `${String(event.description || "尚無說明")}；事件類型 ${eventTypes.list.data?.find((type) => type.id === event.eventTypeId)?.name ?? "未知"}；來源 ${String(event.sourceType)}`,
  })) ?? [];
  const distributionChartData = groups.map((group) => {
    const distribution = group.exposureDistribution as Record<string, unknown>;
    return {
      group: String(group.group),
      minimum: distribution.minimum == null ? null : Number(distribution.minimum),
      firstQuartile: distribution.firstQuartile == null ? null : Number(distribution.firstQuartile),
      median: distribution.median == null ? null : Number(distribution.median),
      thirdQuartile: distribution.thirdQuartile == null ? null : Number(distribution.thirdQuartile),
      maximum: distribution.maximum == null ? null : Number(distribution.maximum),
    };
  });
  const exposureResults = groups.map((group) => group.exposure as Record<string, unknown>);
  const comparisonProvenance = metricKey ? {
    metricKey: `social.first_day.${metricKey}.${aggregation.toLowerCase()}`,
    formulaVersion: Number(exposureResults[0]?.formulaVersion ?? 1),
    quality: [...new Set(exposureResults.map((result) => String(result.quality)))].join("+") || "INSUFFICIENT",
    observationCount: exposureResults.reduce((sum, result) => sum + Number(result.observationCount ?? 0), 0),
    excludedCount: exposureResults.reduce((sum, result) => sum + Number(result.excludedCount ?? 0), 0),
    window: { kind: "POST_PUBLICATION_HOURS", from: `${today.slice(0, 4)}-01-01T00:00:00.000Z`, to: `${today}T23:59:59.999Z`, targetHours: 24, toleranceMinutes: tolerance },
    filters: (comparison.data?.filters as Record<string, unknown> | undefined) ?? {},
    grouping: [groupBy],
    aggregation: aggregation === "DISTRIBUTION" ? "FIVE_NUMBER_DISTRIBUTION_OF_FIRST_DAY_SNAPSHOTS" : aggregation,
    denominatorDefinition: aggregation === "MEAN" ? "有合格首日觀測的內容數" : null,
  } : null;
  const timelineProvenance = timelineMetric ? {
    metricKey: timelineMetric.metricKey,
    formulaVersion: 1,
    quality: [...new Set(timelineSnapshots.map((row) => String(row.quality)))].join("+") || "INSUFFICIENT",
    observationCount: timelineSnapshots.length,
    excludedCount: 0,
    window: { kind: "OBSERVED_AT_RANGE", from: timelineSnapshots[0]?.observedAt ?? null, to: timelineSnapshots.at(-1)?.observedAt ?? null, timezone: "Asia/Taipei" },
    filters: { platformPostId: timelinePostId, socialMetricDefinitionId: timelineMetricId, eventTypeId: timelineEventTypeId || null },
    grouping: ["observedAt"],
    aggregation: "NONE_RAW_SERIES",
    denominatorDefinition: null,
  } : null;

  return <div className="page"><PageHeader eyebrow="CONTENT / PROVENANCE" title="社群內容、首日比較與轉化" description="API、CSV與手動紀錄分開標示；接近 24 小時只會標為最近值，不會冒充精確首日值。" />
    <Panel title="內容比較" index="01" tone="accent" id="social-comparison-evidence">
      <div className="filter-bar">
        <Field label="曝光指標"><Select value={metricKey} onChange={(event) => setMetricKey(event.target.value)}><option value="">請選擇</option>{metrics.list.data?.filter((item) => item.scope === "POST").map((item) => <option key={item.id} value={item.metricKey}>{item.providerMetricName}</option>)}</Select></Field>
        <Field label="曝光聚合"><Select value={aggregation} onChange={(event) => setAggregation(event.target.value as ExposureAggregation)}>{Object.entries(aggregationLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select></Field>
        <Field label="分組欄位"><Select value={groupBy} onChange={(event) => setGroupBy(event.target.value)}>{Object.entries(groupLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</Select></Field>
        <Field label="24 小時容許誤差（分鐘）"><TextInput type="number" min="0" max="1440" value={tolerance} onChange={(event) => setTolerance(Number(event.target.value))} /></Field>
        <Field label="平台篩選"><Select value={platformFilter} onChange={(event) => setPlatformFilter(event.target.value)}><option value="">全部</option>{platforms.list.data?.map((platform) => <option key={platform.id} value={platform.key}>{platform.name}</option>)}</Select></Field>
        <Field label="帳號篩選"><Select value={accountFilter} onChange={(event) => setAccountFilter(event.target.value)}><option value="">全部</option>{accounts.list.data?.filter((account) => !platformFilter || account.platformId === platforms.list.data?.find((platform) => platform.key === platformFilter)?.id).map((account) => <option key={account.id} value={account.id}>{account.displayName}</option>)}</Select></Field>
        <Field label="事業篩選"><Select value={businessFilter} onChange={(event) => setBusinessFilter(event.target.value)}><option value="">全部</option>{businesses.list.data?.map((business) => <option key={business.id} value={business.id}>{business.name}</option>)}</Select></Field>
        <Field label="風格篩選"><Select value={styleFilter} onChange={(event) => setStyleFilter(event.target.value)}><option value="">全部</option>{[...new Set(content.list.data?.map((asset) => asset.style) ?? [])].map((style) => <option key={style} value={style}>{style}</option>)}</Select></Field>
        <Field label="主題篩選"><Select value={topicFilter} onChange={(event) => setTopicFilter(event.target.value)}><option value="">全部</option>{[...new Set(content.list.data?.map((asset) => String(asset.topic)).filter(Boolean) ?? [])].map((topic) => <option key={topic} value={topic}>{topic}</option>)}</Select></Field>
        <Field label="標籤篩選"><Select value={tagFilter} onChange={(event) => setTagFilter(event.target.value)}><option value="">全部</option>{tags.list.data?.map((tag) => <option key={tag.id} value={tag.name}>{tag.name}</option>)}</Select></Field>
      </div>
      {metricKey ? <>
        {aggregation === "DISTRIBUTION" ? <MetricLineChart title={`各${groupLabel}首日曝光分布`} subtitle={`最小值、第一四分位數、中位數、第三四分位數、最大值；四分位數採線性內插；依${groupLabel}分組`} data={distributionChartData} xKey="group" xAxisName={groupLabel} yAxisName="首日曝光分布" unit={metricKey} series={[{ key: "minimum", name: "最小值", color: "#6c7270", dash: "2 3" }, { key: "firstQuartile", name: "第一四分位數", color: "#8a6428" }, { key: "median", name: "中位數", color: "#244f84" }, { key: "thirdQuartile", name: "第三四分位數", color: "#246b46" }, { key: "maximum", name: "最大值", color: "#a1412d", dash: "5 3" }]} definition={`各${groupLabel}中合格首日快照的五數分布；空群組維持缺失，不以0取代。`} source="social_metric_snapshots + platform_posts + content_assets + entity_tags；公式版本 1" sampleSize={groups.reduce((sum, group) => sum + Number((group.exposureDistribution as Record<string, unknown>).count ?? 0), 0)} missingCount={groups.reduce((sum, group) => sum + Number((group.exposure as Record<string, unknown>).missingCount ?? 0), 0)} lastUpdated={String(comparison.data?.calculatedAt ?? "")} provenance={comparisonProvenance} evidenceHref="#social-comparison-evidence" /> : <MetricLineChart title={`各${groupLabel}首日曝光${aggregationLabels[aggregation]}`} subtitle={`目標發布後 24 小時 ± ${tolerance} 分鐘；依${groupLabel}分組`} data={chartData} xKey="group" xAxisName={groupLabel} yAxisName={`曝光${aggregationLabels[aggregation]}`} unit={metricKey} series={[{ key: "exposure", name: `${aggregationLabels[aggregation]} ${metricKey}`, color: "#244f84" }]} definition={`各${groupLabel}中，落在24小時容許誤差內的累積曝光快照${aggregationLabels[aggregation]}；精確、最近值與不足分別保留品質標記。所有畫面篩選同時保存在分析provenance。`} source="social_metric_snapshots + platform_posts + content_assets + entity_tags；公式版本 1" sampleSize={groups.reduce((sum, group) => sum + Number((group.exposure as Record<string, unknown>).sampleSize ?? 0), 0)} missingCount={groups.reduce((sum, group) => sum + Number((group.exposure as Record<string, unknown>).missingCount ?? 0), 0)} lastUpdated={String(comparison.data?.calculatedAt ?? "")} provenance={comparisonProvenance} evidenceHref="#social-comparison-evidence" />}
        {confounders.length ? <div className="warning-line"><strong>已知未控制條件：</strong>{confounders.map((item) => `${item.field}（${Object.entries(item.groups).map(([group, values]) => `${group}: ${values.join("/")}`).join("；")}）`).join("；")}</div> : <p className="support-copy">目前群組間未發現平台、帳號、事業或主題條件差異；這不代表因果關係。</p>}
        <div className="data-table-wrap"><table className="data-table"><thead><tr><th>{groupLabel}</th><th>曝光{aggregationLabels[aggregation]}</th><th>成交總數</th><th>總和比轉化率</th><th>個別比率平均</th><th>品質／缺失</th><th>納入／排除依據</th></tr></thead><tbody>{groups.map((group) => { const exposure = group.exposure as Record<string, unknown>; const distribution = group.exposureDistribution as Record<string, unknown>; const conversionsResult = group.conversions as Record<string, unknown>; const rate = group.conversionRate as Record<string, unknown>; const mean = group.meanIndividualConversionRate as Record<string, unknown>; const selections = group.postSelections as Array<Record<string, unknown>>; return <tr key={String(group.group)}><td>{String(group.group)}</td><td>{aggregation === "DISTRIBUTION" ? `n=${String(distribution.count)}；${String(distribution.minimum ?? "—")} / ${String(distribution.firstQuartile ?? "—")} / ${String(distribution.median ?? "—")} / ${String(distribution.thirdQuartile ?? "—")} / ${String(distribution.maximum ?? "—")}` : String(exposure.value ?? "資料不足")}</td><td>{String(conversionsResult.value ?? "—")}</td><td>{rate.value == null ? "資料不足" : `${Number(rate.value).toFixed(4)}%`}</td><td>{mean.value == null ? "資料不足" : `${Number(mean.value).toFixed(4)}%`}</td><td><StatusMark tone={exposure.quality === "EXACT" ? "good" : exposure.quality === "NEAREST" ? "warn" : "danger"}>{String(exposure.quality)}</StatusMark> · 缺 {String(exposure.missingCount)}</td><td><details><summary>查看 {selections.length} 篇</summary>{selections.map((selection) => <small key={String(selection.postId)}>{String(selection.postId)} · {String(selection.quality)} · 偏差 {selection.deviationSeconds == null ? "未知" : `${String(selection.deviationSeconds)}秒`} {selection.excludedReason ? `· ${String(selection.excludedReason)}` : ""}</small>)}</details></td></tr>; })}</tbody></table></div>
      </> : <EmptyState title="選擇一個貼文曝光指標" detail="建立或同步貼文層級指標後才能比較。" />}
    </Panel>
    <Panel title="貼文數據與事件時間線" index="01A"><div className="filter-bar"><Field label="貼文"><Select value={timelinePostId} onChange={(event) => setTimelinePostId(event.target.value)}><option value="">請選擇</option>{posts.list.data?.map((post) => <option key={post.id} value={post.id}>{content.list.data?.find((asset) => asset.id === post.contentAssetId)?.title ?? post.id}</option>)}</Select></Field><Field label="指標"><Select value={timelineMetricId} onChange={(event) => setTimelineMetricId(event.target.value)}><option value="">請選擇</option>{metrics.list.data?.filter((metric) => metric.scope === "POST").map((metric) => <option key={metric.id} value={metric.id}>{metric.providerMetricName}</option>)}</Select></Field><Field label="事件類型篩選"><Select value={timelineEventTypeId} onChange={(event) => setTimelineEventTypeId(event.target.value)}><option value="">全部事件</option>{eventTypes.list.data?.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</Select></Field></div>{timelinePostId && timelineMetricId ? <MetricLineChart title="貼文觀測與事件" subtitle="事件以實際發生instant疊在觀測時間軸；顯示為Asia/Taipei" data={timelineData} xKey="observedAt" xAxisName="觀測時間（Asia/Taipei）" yAxisName={timelineMetric?.providerMetricName ?? "值"} unit={timelineMetric?.unit ?? "unknown"} series={[{ key: "value", name: timelineMetric?.providerMetricName ?? "觀測值", color: "#244f84" }]} markers={timelineMarkers} definition="貼文同一指標的原始時間序列；紅色虛線為事件instant，不改變原始觀測。事件可依類型篩選，並以hover、鍵盤focus或點擊查看說明。" source="social_metric_snapshots + events" sampleSize={timelineData.length} missingCount={0} lastUpdated={timelineSnapshots.at(-1) ? String(timelineSnapshots.at(-1)?.updatedAt ?? timelineSnapshots.at(-1)?.observedAt) : null} provenance={timelineProvenance} evidenceHref="#social-snapshot-records" /> : <EmptyState title="選擇貼文與指標" detail="圖上只會顯示正式快照及真實事件，不產生示範曲線。" />}</Panel>
    <div className="three-column-layout"><Panel title="平台與帳號" index="02"><form className="form-grid" onSubmit={addPlatform}><Field label="平台鍵"><TextInput name="key" pattern="[a-z][a-z0-9_-]+" required /></Field><Field label="平台名稱"><TextInput name="name" required /></Field><Field label="命名空間"><TextInput name="namespace" required /></Field><button className="button">新增手動平台</button></form><form className="form-grid section-break" onSubmit={addAccount}><Field label="平台"><Select name="platformId" required>{platforms.list.data?.filter((item) => !item.archivedAt).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="帳號顯示名稱"><TextInput name="displayName" required /></Field><button className="button button--quiet">新增帳號</button></form></Panel>
      <Panel title="內容與發布" index="03"><form className="form-grid" onSubmit={addContent}><Field label="所屬事業"><Select name="businessId"><option value="">未關聯</option>{businesses.list.data?.map((business) => <option key={business.id} value={business.id}>{business.name}</option>)}</Select></Field><Field label="標題"><TextInput name="title" required /></Field><Field label="主題"><TextInput name="topic" /></Field><Field label="風格"><TextInput name="style" required /></Field><Field label="格式"><TextInput name="format" /></Field><Field label="長度"><TextInput name="lengthValue" type="number" min="0" /></Field><Field label="長度單位"><TextInput name="lengthUnit" /></Field><Field label="活動"><TextInput name="campaign" /></Field><Field label="說明"><TextArea name="description" /></Field><button className="button">建立內容母體</button></form><form className="form-grid section-break" onSubmit={addPost}><Field label="內容"><Select name="contentAssetId" required>{content.list.data?.filter((item) => !item.archivedAt).map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</Select></Field><Field label="帳號"><Select name="socialAccountId" required>{accounts.list.data?.filter((item) => !item.archivedAt).map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</Select></Field><Field label="發布時間"><TextInput name="publishedAt" type="datetime-local" required /></Field><Field label="外部貼文 ID"><TextInput name="externalPostId" /></Field><Field label="網址"><TextInput name="permalink" type="url" /></Field><Field label="平台格式"><TextInput name="platformFormat" /></Field><button className="button button--quiet">記錄發布</button></form></Panel>
      <Panel title="指標定義" index="04"><form className="form-grid" onSubmit={addMetric}><Field label="平台"><Select name="platformId" required>{platforms.list.data?.filter((item) => !item.archivedAt).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="指標鍵"><TextInput name="metricKey" pattern="[a-z][a-z0-9_.-]+" required /></Field><Field label="來源欄名"><TextInput name="providerMetricName" required /></Field><Field label="來源定義"><TextArea name="providerDefinition" required /></Field><Field label="單位"><TextInput name="unit" required /></Field><Field label="範圍"><Select name="scope"><option value="POST">貼文</option><option value="ACCOUNT">帳號</option></Select></Field><Field label="可比較族群"><TextInput name="comparableFamily" /></Field><label className="check-field"><input name="isCumulative" type="checkbox" />累積值</label><button className="button">建立定義</button></form></Panel></div>
    <Panel title="社群定義與內容管理" index="04A">
      <div className="data-table-wrap"><table className="data-table"><thead><tr><th>類別</th><th>名稱</th><th>來源／狀態</th><th>操作</th></tr></thead><tbody>{platforms.list.data?.map((row) => <tr key={row.id}><td>平台</td><td>{row.name}<small>{row.key}</small></td><td>{String(row.providerKind)} · {row.archivedAt ? "已封存" : "啟用"}</td><td>{row.providerKind === "MANUAL" ? <details className="inline-editor"><summary>編輯</summary><form className="form-grid" onSubmit={(event) => editPlatform(event, row)}><Field label="平台鍵"><TextInput name="key" defaultValue={row.key} required /></Field><Field label="名稱"><TextInput name="name" defaultValue={row.name} required /></Field><Field label="命名空間"><TextInput name="namespace" defaultValue={String(row.metricNamespace)} required /></Field><button className="button">保存</button><button className="button button--quiet" type="button" onClick={() => platforms.archive.mutate({ id: row.id, version: row.version, restore: Boolean(row.archivedAt) })}>{row.archivedAt ? "恢復" : "封存"}</button></form></details> : <span>正式Provider定義不可手動改寫</span>}</td></tr>)}{accounts.list.data?.map((row) => <tr key={row.id}><td>帳號</td><td>{row.displayName}</td><td>{String(row.sourceType)} · {row.archivedAt ? "已封存" : "啟用"}</td><td>{row.sourceType === "MANUAL" ? <details className="inline-editor"><summary>編輯</summary><form className="form-grid" onSubmit={(event) => editAccount(event, row)}><Field label="平台"><Select name="platformId" defaultValue={row.platformId}>{platforms.list.data?.filter((platform) => !platform.archivedAt || platform.id === row.platformId).map((platform) => <option key={platform.id} value={platform.id}>{platform.name}</option>)}</Select></Field><Field label="顯示名稱"><TextInput name="displayName" defaultValue={row.displayName} required /></Field><Field label="帳號類型"><TextInput name="accountKind" defaultValue={String(row.accountKind)} required /></Field><Field label="時區"><TextInput name="timezone" defaultValue={String(row.timezone)} required /></Field><button className="button">保存</button><button className="button button--quiet" type="button" onClick={() => accounts.archive.mutate({ id: row.id, version: row.version, restore: Boolean(row.archivedAt) })}>{row.archivedAt ? "恢復" : "封存"}</button></form></details> : <span>Provider同步帳號不可手動改寫</span>}</td></tr>)}</tbody></table></div>
      <div className="data-table-wrap"><table className="data-table"><thead><tr><th>內容</th><th>事業／風格</th><th>狀態</th><th>操作</th></tr></thead><tbody>{content.list.data?.map((row) => <tr key={row.id}><td>{row.title}</td><td>{businesses.list.data?.find((business) => business.id === row.businessId)?.name ?? "未關聯"} · {row.style}</td><td>{row.archivedAt ? "已封存" : "啟用"}</td><td><details className="inline-editor"><summary>編輯內容</summary><form className="form-grid" onSubmit={(event) => editContent(event, row)}><Field label="事業"><Select name="businessId" defaultValue={String(row.businessId ?? "")}><option value="">未關聯</option>{businesses.list.data?.map((business) => <option key={business.id} value={business.id}>{business.name}</option>)}</Select></Field><Field label="標題"><TextInput name="title" defaultValue={row.title} required /></Field><Field label="主題"><TextInput name="topic" defaultValue={String(row.topic ?? "")} /></Field><Field label="風格"><TextInput name="style" defaultValue={row.style} required /></Field><Field label="格式"><TextInput name="format" defaultValue={String(row.format ?? "")} /></Field><Field label="長度"><TextInput name="lengthValue" type="number" min="0" defaultValue={row.lengthValue == null ? "" : Number(row.lengthValue)} /></Field><Field label="長度單位"><TextInput name="lengthUnit" defaultValue={String(row.lengthUnit ?? "")} /></Field><Field label="活動"><TextInput name="campaign" defaultValue={String(row.campaign ?? "")} /></Field><Field label="說明"><TextArea name="description" defaultValue={String(row.description ?? "")} /></Field><button className="button">保存</button><button className="button button--quiet" type="button" onClick={() => content.archive.mutate({ id: row.id, version: row.version, restore: Boolean(row.archivedAt) })}>{row.archivedAt ? "恢復" : "封存"}</button></form></details></td></tr>)}</tbody></table></div>
      <div className="data-table-wrap"><table className="data-table"><thead><tr><th>指標</th><th>範圍／單位</th><th>來源／狀態</th><th>操作</th></tr></thead><tbody>{metrics.list.data?.map((row) => <tr key={row.id}><td>{row.providerMetricName}<small>{row.metricKey}</small></td><td>{row.scope} · {row.unit}</td><td>{String(row.sourceType)} · {row.archivedAt ? "已封存" : "啟用"}</td><td>{row.sourceType === "MANUAL" ? <details className="inline-editor"><summary>編輯指標</summary><form className="form-grid" onSubmit={(event) => editMetric(event, row)}><Field label="平台"><Select name="platformId" defaultValue={String(row.platformId)}>{platforms.list.data?.filter((platform) => !platform.archivedAt || platform.id === row.platformId).map((platform) => <option key={platform.id} value={platform.id}>{platform.name}</option>)}</Select></Field><Field label="指標鍵"><TextInput name="metricKey" defaultValue={row.metricKey} required /></Field><Field label="來源欄名"><TextInput name="providerMetricName" defaultValue={row.providerMetricName} required /></Field><Field label="來源定義"><TextArea name="providerDefinition" defaultValue={String(row.providerDefinition)} required /></Field><Field label="單位"><TextInput name="unit" defaultValue={row.unit} required /></Field><Field label="範圍"><Select name="scope" defaultValue={row.scope}><option value="POST">貼文</option><option value="ACCOUNT">帳號</option></Select></Field><Field label="可比較族群"><TextInput name="comparableFamily" defaultValue={String(row.comparableFamily ?? "")} /></Field><label className="check-field"><input name="isCumulative" type="checkbox" defaultChecked={row.isCumulative} />累積值</label><button className="button">保存</button><button className="button button--quiet" type="button" onClick={() => metrics.archive.mutate({ id: row.id, version: row.version, restore: Boolean(row.archivedAt) })}>{row.archivedAt ? "恢復" : "封存"}</button></form></details> : <span>Provider指標定義不可手動改寫</span>}</td></tr>)}</tbody></table></div>
      <FormError error={platforms.update.error || platforms.archive.error || accounts.update.error || accounts.archive.error || content.update.error || content.archive.error || metrics.update.error || metrics.archive.error} />
    </Panel>
    <div className="split-layout"><Panel title="手動快照" index="05"><form className="form-grid" onSubmit={addSnapshot}><Field label="指標"><Select name="metricId" required>{metrics.list.data?.map((item) => <option key={item.id} value={item.id}>{item.providerMetricName}</option>)}</Select></Field><Field label="貼文（選貼文時帳號留空）"><Select name="platformPostId"><option value="">帳號層級</option>{posts.list.data?.map((item) => <option key={item.id} value={item.id}>{content.list.data?.find((asset) => asset.id === item.contentAssetId)?.title ?? item.id}</option>)}</Select></Field><Field label="帳號"><Select name="socialAccountId"><option value="">請選擇</option>{accounts.list.data?.map((item) => <option key={item.id} value={item.id}>{item.displayName}</option>)}</Select></Field><Field label="觀測時間"><TextInput name="observedAt" type="datetime-local" required /></Field><Field label="值"><TextInput name="value" inputMode="decimal" required /></Field><FormError error={snapshots.create.error} /><button className="button">保存快照</button></form></Panel>
      <Panel title="手動成交與轉化" index="06"><form className="form-grid" onSubmit={addConversion}><Field label="歸因貼文"><Select name="postId" required>{posts.list.data?.map((item) => <option key={item.id} value={item.id}>{content.list.data?.find((asset) => asset.id === item.contentAssetId)?.title ?? item.id}</option>)}</Select></Field><Field label="確認時間"><TextInput name="confirmedAt" type="datetime-local" required /></Field><Field label="成交數"><TextInput name="countValue" type="number" min="0" required /></Field><Field label="分母指標鍵"><TextInput name="denominatorMetricKey" required /></Field><Field label="活動"><TextInput name="campaign" /></Field><Field label="歸因證據與理由"><TextArea name="attributionNote" required /></Field><button className="button">保存成交</button></form>{conversions.list.data?.length ? <div className="data-table-wrap section-break"><table className="data-table"><thead><tr><th>貼文</th><th>成交</th><th>分母</th><th>確認時間</th><th>操作</th></tr></thead><tbody>{conversions.list.data.map((row) => <tr key={String(row.id)}><td>{content.list.data?.find((asset) => asset.id === row.contentAssetId)?.title ?? String(row.platformPostId ?? "未關聯")}</td><td>{String(row.countValue)}</td><td>{String(row.denominatorMetricKey)}</td><td>{new Date(String(row.confirmedAt)).toLocaleString("zh-TW")}</td><td><details className="inline-editor"><summary>修改成交</summary><form className="form-grid" onSubmit={(event) => editConversion(event, row)}><Field label="成交數"><TextInput name="countValue" type="number" min="0" defaultValue={Number(row.countValue)} required /></Field><Field label="確認時間"><TextInput name="confirmedAt" type="datetime-local" defaultValue={String(row.confirmedAt).slice(0, 16)} required /></Field><Field label="分母指標鍵"><TextInput name="denominatorMetricKey" defaultValue={String(row.denominatorMetricKey)} required /></Field><Field label="歸因證據與理由"><TextArea name="attributionNote" defaultValue={String(row.attributionNote ?? "")} required /></Field><button className="button">保存修改</button><button className="button button--quiet" type="button" onClick={() => conversions.archive.mutate({ id: String(row.id), version: Number(row.version) })}>刪除</button></form></details></td></tr>)}</tbody></table></div> : <EmptyState title="尚無手動成交" detail="建立成交紀錄後，可在此修改並立即重算轉化率。" />}</Panel></div>
    <Panel title="社群 CSV 匯入" index="07"><p className="support-copy">CSV需提供貼文或帳號UUID、觀測時間與數值；後端保存映射、原始檔、逐列結果並以穩定鍵去重。</p><StructuredCsvImport moduleKey="social" definitions={metrics.list.data?.map((metric) => ({ id: metric.id, label: `${metric.providerMetricName} · ${metric.unit}` })) ?? []} onImported={async () => { await snapshots.list.refetch(); }} /></Panel>
    <Panel title="最近發布" index="08">{!posts.list.data?.length ? <EmptyState title="尚無發布紀錄" detail="連線不會自動生成示範貼文；授權同步或手動登記後才出現。" /> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>內容</th><th>發布時間</th><th>來源</th><th>狀態</th><th>操作</th></tr></thead><tbody>{posts.list.data.map((item) => <tr key={item.id}><td>{content.list.data?.find((asset) => asset.id === item.contentAssetId)?.title ?? item.id}</td><td>{new Date(item.publishedAt).toLocaleString("zh-TW")}</td><td>{String(item.sourceType)}</td><td><StatusMark tone={item.archivedAt ? "neutral" : item.pending ? "pending" : "good"}>{item.archivedAt ? "已封存" : item.pending ? "待同步" : "已保存"}</StatusMark></td><td>{item.sourceType === "MANUAL" ? <details className="inline-editor"><summary>編輯發布</summary><form className="form-grid" onSubmit={(event) => editPost(event, item)}><Field label="內容"><Select name="contentAssetId" defaultValue={item.contentAssetId}>{content.list.data?.filter((asset) => !asset.archivedAt || asset.id === item.contentAssetId).map((asset) => <option key={asset.id} value={asset.id}>{asset.title}</option>)}</Select></Field><Field label="帳號"><Select name="socialAccountId" defaultValue={String(item.socialAccountId)}>{accounts.list.data?.filter((account) => !account.archivedAt || account.id === item.socialAccountId).map((account) => <option key={account.id} value={account.id}>{account.displayName}</option>)}</Select></Field><Field label="發布時間"><TextInput name="publishedAt" type="datetime-local" defaultValue={item.publishedAt.slice(0, 16)} required /></Field><Field label="外部貼文 ID"><TextInput name="externalPostId" defaultValue={String(item.externalPostId ?? "")} /></Field><Field label="網址"><TextInput name="permalink" type="url" defaultValue={String(item.permalink ?? "")} /></Field><Field label="平台格式"><TextInput name="platformFormat" defaultValue={String(item.platformFormat ?? "")} /></Field><button className="button">保存</button><button className="button button--quiet" type="button" onClick={() => posts.archive.mutate({ id: item.id, version: item.version, restore: Boolean(item.archivedAt) })}>{item.archivedAt ? "恢復" : "封存"}</button></form></details> : <span>Provider發布不可手動改寫</span>}</td></tr>)}</tbody></table></div>}</Panel>
    <Panel title="手動快照紀錄" index="09" id="social-snapshot-records">{!snapshots.list.data?.length ? <EmptyState title="尚無社群快照" detail="手動輸入、CSV或正式provider同步後才會出現資料。" /> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>觀測時間</th><th>指標</th><th>值</th><th>來源／品質</th><th>操作</th></tr></thead><tbody>{snapshots.list.data.map((row) => { const metric = metrics.list.data?.find((item) => item.id === row.socialMetricDefinitionId); return <tr key={String(row.id)}><td>{new Date(String(row.observedAt)).toLocaleString("zh-TW")}</td><td>{metric?.providerMetricName ?? String(row.socialMetricDefinitionId)}</td><td>{String(row.valueDecimal)} {metric?.unit ?? ""}</td><td>{String(row.sourceType)} · {String(row.quality)}</td><td>{row.sourceType === "MANUAL" ? <details className="inline-editor"><summary>編輯</summary><form className="form-grid" onSubmit={(event) => editSocialSnapshot(event, row)}><Field label="觀測時間"><TextInput name="observedAt" type="datetime-local" defaultValue={String(row.observedAt).slice(0, 16)} required /></Field><Field label="值"><TextInput name="value" defaultValue={String(row.valueDecimal)} required /></Field><button className="button">保存修改</button><button className="button button--quiet" type="button" onClick={() => snapshots.archive.mutate({ id: String(row.id), version: Number(row.version) })}>刪除</button></form></details> : <span>來源資料不可手動改寫</span>}</td></tr>; })}</tbody></table></div>}</Panel>
    <Panel title="內容標籤關聯" index="10">{content.list.data?.length && tags.list.data?.length ? <form className="inline-form" onSubmit={(event) => void addContentTag(event)}><Field label="內容"><Select name="contentAssetId" required><option value="">請選擇</option>{content.list.data.map((asset) => <option key={asset.id} value={asset.id}>{asset.title}</option>)}</Select></Field><Field label="標籤"><Select name="tagId" required><option value="">請選擇</option>{tags.list.data.map((tag) => <option key={tag.id} value={tag.id}>{tag.name}</option>)}</Select></Field><button className="button">加上標籤</button></form> : <EmptyState title="需要內容與標籤" detail="先建立內容與標籤，再建立可供比較篩選的正式關聯。" />}</Panel>
    <Panel title="保存的比較與圖表檢視" index="11"><form className="inline-form" onSubmit={(event) => void saveComparisonDefinition(event)}><Field label="檢視名稱"><TextInput name="name" required /></Field><button className="button" disabled={!metricKey}>保存目前篩選與圖表</button></form>{comparisonDefinitions.list.data?.length ? <div className="data-table-wrap"><table className="data-table"><thead><tr><th>名稱</th><th>指標</th><th>聚合</th><th>分組</th><th>容許誤差</th><th>狀態</th><th>操作</th></tr></thead><tbody>{comparisonDefinitions.list.data.map((definition) => <tr key={definition.id}><td>{definition.name}</td><td>{definition.metricKey}</td><td>{aggregationLabels[definition.aggregation] ?? definition.aggregation}</td><td>{definition.groupBy.map((key) => groupLabels[key] ?? key).join("、")}</td><td>± {definition.toleranceMinutes} 分鐘</td><td><StatusMark tone={definition.archivedAt ? "neutral" : "good"}>{definition.archivedAt ? "已封存" : "可使用"}</StatusMark></td><td><button className="button button--quiet" type="button" onClick={() => applyComparisonDefinition(definition)}>套用</button><button className="button button--quiet" type="button" onClick={() => comparisonDefinitions.archive.mutate({ id: definition.id, version: Number(definition.version), restore: Boolean(definition.archivedAt) })}>{definition.archivedAt ? "恢復" : "封存"}</button></td></tr>)}</tbody></table></div> : <EmptyState title="尚無保存檢視" detail="選好比較指標、聚合、分組、容許誤差與篩選後，可保存為正式檢視。" />}</Panel>
  </div>;
}
